name: ci

on:
    pull_request:
        branches: [main]

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v5

            - name: Set up Go
              uses: actions/setup-go@v6
              with:
                  go-version: "1.25"

            - name: Run unit tests
              run: go test ./... -cover
    style:
        name: Style
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v5

            - name: Set up Go
              uses: actions/setup-go@v6
              with:
                  go-version: "1.25"

            - name: Formatting check
              run: test -z $(go fmt ./...)

            - name: Lint with staticcheck
              uses: dominikh/staticcheck-action@v1
              with:
                  version: "latest"
                  install-go: false
